name: DEV Pipeline

on:
  push:
    branches: [develop]

jobs:
  build-test-deploy:
    name: Build, Test & Deploy to DEV
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Publish
        run: dotnet publish SmartExpenseTracker.Api/SmartExpenseTracker_Api.csproj --configuration Release --output ./publish

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: Deploy to DEV
        uses: Azure/functions-action@v1
        with:
          app-name: func-smartexpensetracker-dev
          package: ./publish
